version: '3.8'

services:
  django_app
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8071:8071"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
